/**
 * Replay storage.
 *
 * Files on disk, because that is genuinely all this needs: a replay is written
 * once by the CLI and read many times by browsers. No database, no queue, no
 * job runner — the server never executes anything (web plan §3).
 */
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { isReplayFile, summarise, type ReplayFile, type ReplaySummary } from '@spark/replay';

@Injectable()
export class ReplaysService {
  private readonly log = new Logger('replays');
  private readonly dir = resolve(process.env['SPARK_REPLAY_DIR'] ?? 'replays');
  private readonly summaries = new Map<string, ReplaySummary>();

  constructor() {
    mkdirSync(this.dir, { recursive: true });
    this.reindex();
  }

  /** Rebuilds the summary index from disk, so replays survive a restart. */
  private reindex(): void {
    this.summaries.clear();
    for (const name of readdirSync(this.dir)) {
      if (!name.endsWith('.json')) continue;
      const path = join(this.dir, name);
      try {
        const raw: unknown = JSON.parse(readFileSync(path, 'utf8'));
        if (!isReplayFile(raw)) continue;
        this.summaries.set(raw.id, summarise(raw, statSync(path).size));
      } catch (err) {
        this.log.warn(`skipping ${name}: ${(err as Error).message}`);
      }
    }
    this.log.log(`indexed ${this.summaries.size} replays in ${this.dir}`);
  }

  list(): ReplaySummary[] {
    return [...this.summaries.values()].sort((a, b) => b.finishedAt.localeCompare(a.finishedAt));
  }

  get(id: string): ReplayFile {
    const path = this.pathFor(id);
    if (!existsSync(path)) throw new NotFoundException(`no replay ${id}`);
    const raw: unknown = JSON.parse(readFileSync(path, 'utf8'));
    if (!isReplayFile(raw)) throw new NotFoundException(`${id} is not a replay`);
    return raw;
  }

  save(replay: ReplayFile): ReplaySummary {
    const path = this.pathFor(replay.id);
    const body = JSON.stringify(replay);
    writeFileSync(path, body);
    const summary = summarise(replay, body.length);
    this.summaries.set(replay.id, summary);
    this.log.log(`stored ${replay.id} (${replay.bots.A.name} vs ${replay.bots.B.name})`);
    return summary;
  }

  /** Ids are generated by the CLI; refuse anything that could escape the directory. */
  private pathFor(id: string): string {
    if (!/^[A-Za-z0-9._-]{1,80}$/.test(id)) throw new NotFoundException('bad replay id');
    return join(this.dir, `${id}.json`);
  }
}
