/**
 * Replay storage.
 *
 * Files on disk, because that is genuinely all this needs: a replay is written
 * once by the CLI and read many times by browsers. No database, no queue, no
 * job runner — the server never executes anything (web plan §3).
 *
 * A file name is not an id. The CLI lets a match be written anywhere the author
 * likes (`spark run --replay replays/demo.json`), so the index remembers which
 * path each replay was found at and reads go through that — otherwise the list
 * advertises ids that cannot be fetched.
 */
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { isReplayFile, summarise, type ReplayFile, type ReplaySummary } from '@spark/replay';

@Injectable()
export class ReplaysService {
  private readonly log = new Logger('replays');
  private readonly dir = resolve(process.env['SPARK_REPLAY_DIR'] ?? 'replays');
  private readonly summaries = new Map<string, ReplaySummary>();
  private readonly paths = new Map<string, string>();

  constructor() {
    mkdirSync(this.dir, { recursive: true });
    this.reindex();
  }

  /** Rebuilds the summary index from disk, so replays survive a restart. */
  private reindex(): void {
    this.summaries.clear();
    this.paths.clear();
    for (const name of readdirSync(this.dir)) {
      if (!name.endsWith('.json')) continue;
      const path = join(this.dir, name);
      try {
        const raw: unknown = JSON.parse(readFileSync(path, 'utf8'));
        if (!isReplayFile(raw)) continue;
        // An id we cannot address is an id we must not list.
        if (!this.isAddressable(raw.id)) {
          this.log.warn(`skipping ${name}: no usable replay id`);
          continue;
        }
        this.summaries.set(raw.id, summarise(raw, statSync(path).size));
        this.paths.set(raw.id, path);
      } catch (err) {
        this.log.warn(`skipping ${name}: ${(err as Error).message}`);
      }
    }
    this.log.log(`indexed ${this.summaries.size} replays in ${this.dir}`);
  }

  list(): ReplaySummary[] {
    return [...this.summaries.values()].sort((a, b) => b.finishedAt.localeCompare(a.finishedAt));
  }

  get(id: string): ReplayFile {
    if (!this.isAddressable(id)) throw new NotFoundException('bad replay id');
    // Indexed replays keep the path they were found at; anything dropped in
    // after startup is still found under the name this service would write.
    const path = this.paths.get(id) ?? this.pathFor(id);
    if (!existsSync(path)) throw new NotFoundException(`no replay ${id}`);
    const raw: unknown = JSON.parse(readFileSync(path, 'utf8'));
    if (!isReplayFile(raw)) throw new NotFoundException(`${id} is not a replay`);
    return raw;
  }

  save(replay: ReplayFile): ReplaySummary {
    const path = this.pathFor(replay.id);
    const body = JSON.stringify(replay);
    writeFileSync(path, body);
    const summary = summarise(replay, body.length);
    this.summaries.set(replay.id, summary);
    this.paths.set(replay.id, path);
    this.log.log(`stored ${replay.id} (${replay.bots.A.name} vs ${replay.bots.B.name})`);
    return summary;
  }

  /** Ids are generated by the CLI; refuse anything that could escape the directory. */
  private isAddressable(id: unknown): id is string {
    return typeof id === 'string' && /^[A-Za-z0-9._-]{1,80}$/.test(id);
  }

  private pathFor(id: string): string {
    if (!this.isAddressable(id)) throw new NotFoundException('bad replay id');
    return join(this.dir, `${id}.json`);
  }
}
