/**
 * The replay file (passport §16, amended by web plan §10).
 *
 * A replay is the map seed, a rules snapshot, the locked spellbooks and the
 * ordered log of bot action packets. Because the engine is deterministic that
 * is enough to reconstruct the match exactly — which is what makes a tournament
 * dispute resolvable, and what lets the browser rebuild every frame locally
 * instead of streaming world state.
 *
 * The web plan adds three things to the v0.1 file, all additive:
 *
 *  - `events` per turn: the structured event log, generated by the engine
 *    rather than the viewer, so the ASCII and web viewers cannot disagree.
 *  - `paths` per turn: swept-path segments with fractional collision times,
 *    for smooth playback.
 *  - `keyframes`: full round snapshots every few turns, for backward seeking.
 */
import type { ActionsMessage, Rules, Side, SpellTemplate } from '@spark/protocol';
import type { EngineEvent, MatchResult, ObjectPath, RoundSnapshot } from '@spark/engine';

export const REPLAY_VERSION = '0.2.0';

/** How often a keyframe is written, in turns. Web plan §4 suggests every 5. */
export const KEYFRAME_INTERVAL = 5;

export interface ReplayBotInfo {
  readonly name: string;
  readonly command: readonly string[];
  readonly pagesUsed: number;
}

export interface ReplayTurn {
  readonly round: number;
  readonly turn: number;
  readonly side: Side;
  /** null means the bot timed out or crashed and forfeited the turn. */
  readonly actions: ActionsMessage | null;
  readonly elapsedMs: number;
  readonly stderr: readonly string[];
  /** Events this turn produced, in order. */
  readonly events: readonly EngineEvent[];
  /** Swept paths this turn produced, for interpolated playback. */
  readonly paths: readonly ObjectPath[];
  /** State hash after this turn, so a viewer can prove it reconstructed correctly. */
  readonly hash: string;
}

export interface ReplayKeyframe {
  /** Index into `turns` immediately after which this snapshot was taken. */
  readonly afterTurnIndex: number;
  readonly round: number;
  readonly snapshot: RoundSnapshot;
}

export interface ReplayRoundInfo {
  readonly round: number;
  readonly game: number;
  readonly firstMover: Side;
  /** Index of the first entry in `turns` belonging to this round. */
  readonly firstTurnIndex: number;
  readonly turnCount: number;
  readonly winner: Side | null;
  readonly reason: string;
}

export interface ReplayFile {
  readonly version: string;
  readonly id: string;
  readonly seed: string;
  readonly rules: Rules;
  readonly bots: Readonly<Record<Side, ReplayBotInfo>>;
  readonly spellbooks: Readonly<Record<Side, readonly SpellTemplate[]>>;
  readonly rounds: readonly ReplayRoundInfo[];
  readonly turns: readonly ReplayTurn[];
  readonly keyframes: readonly ReplayKeyframe[];
  readonly result: MatchResult;
  readonly finishedAt: string;
  /**
   * True when the match did not run to completion — the CLI was stopped, or
   * crashed, part way through. The turns present are still real and still
   * reproduce; there is just no result and there are no keyframes, so seeking
   * backwards replays from the start of the round.
   */
  readonly partial?: boolean;
}

/** Summary shown in the match list, without shipping the whole file. */
export interface ReplaySummary {
  readonly id: string;
  readonly seed: string;
  readonly bots: Readonly<Record<Side, string>>;
  readonly result: MatchResult;
  readonly turnCount: number;
  readonly finishedAt: string;
  readonly sizeBytes?: number;
  readonly partial?: boolean;
}

/**
 * Assembles a replay from a live stream that stopped early.
 *
 * A producer that disconnects without an `end` frame has still played real
 * turns, and someone holding the link should get to see them rather than a 404.
 * Round metadata is derived from the turns themselves, because the live header
 * is sent before the first round has finished.
 */
export function finaliseLive(header: ReplayFile, turns: readonly ReplayTurn[]): ReplayFile {
  const rounds: ReplayRoundInfo[] = [];
  turns.forEach((t, index) => {
    const last = rounds[rounds.length - 1];
    if (!last || last.round !== t.round) {
      rounds.push({
        round: t.round,
        game: Math.ceil(t.round / Math.max(1, header.rules.match.roundsPerGame)),
        firstMover: t.round % 2 === 1 ? 'A' : 'B',
        firstTurnIndex: index,
        turnCount: 1,
        winner: null,
        reason: 'interrupted',
      });
      return;
    }
    rounds[rounds.length - 1] = { ...last, turnCount: last.turnCount + 1 };
  });

  return {
    ...header,
    rounds,
    turns: [...turns],
    keyframes: [],
    partial: true,
    // invariant-ok(determinism): file metadata, not simulation input
    finishedAt: new Date().toISOString(),
  };
}

export function summarise(replay: ReplayFile, sizeBytes?: number): ReplaySummary {
  return {
    id: replay.id,
    seed: replay.seed,
    bots: { A: replay.bots.A.name, B: replay.bots.B.name },
    result: replay.result,
    turnCount: replay.turns.length,
    finishedAt: replay.finishedAt,
    ...(replay.partial ? { partial: true } : {}),
    ...(sizeBytes === undefined ? {} : { sizeBytes }),
  };
}

export function isReplayFile(v: unknown): v is ReplayFile {
  if (typeof v !== 'object' || v === null) return false;
  const r = v as Record<string, unknown>;
  return (
    typeof r['version'] === 'string' &&
    typeof r['seed'] === 'string' &&
    Array.isArray(r['turns']) &&
    Array.isArray(r['rounds']) &&
    typeof r['rules'] === 'object' &&
    r['rules'] !== null
  );
}
